baseURL = 'https://shakyasimha.github.io/'
languageCode = 'en-us'
title = 'Sushovan M. Shakya'
theme = 'not-much'

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/shakyasimha"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Connect"
  url = "/connect/"
  weight = 5